name: recent-activity

on:
  schedule:
    - cron: "37 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@v0.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          GH_USERNAME: AliSoleimaniNet
          MAX_LINES: 6
          COMMIT_MSG: "chore: update recent activity"
          COMMIT_NAME: github-actions[bot]
          COMMIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          TARGET_FILE: README.md
